"""add_missing_user_columns

Revision ID: 314d27135fdd
Revises: f47628016f87
Create Date: 2025-12-27 20:30:08.714451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314d27135fdd'
down_revision: Union[str, Sequence[str], None] = 'f47628016f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type explicitly for PostgreSQL
    sync_status_enum = sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'NEVER', name='integrationsyncstatus')
    sync_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('integrations', sa.Column('sync_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'NEVER', name='integrationsyncstatus'), nullable=True))
    op.add_column('integrations', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('integrations', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    op.drop_column('integrations', 'error_message')
    op.drop_column('integrations', 'last_sync_at')
    op.drop_column('integrations', 'sync_status')
    
    # Drop the Enum type
    sync_status_enum = sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'NEVER', name='integrationsyncstatus')
    sync_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
