"""convert_goals_to_jsonb

Revision ID: f0531eaadde1
Revises: eaac19f4761b
Create Date: 2026-01-16 22:42:04.076427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0531eaadde1'
down_revision: Union[str, Sequence[str], None] = 'eaac19f4761b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('type', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('state', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('daily_budget', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('campaigns', sa.Column('strategy', sa.String(), nullable=True))
    op.alter_column('integrations', 'selected_goals',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='selected_goals::jsonb',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrations', 'selected_goals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('campaigns', 'strategy')
    op.drop_column('campaigns', 'daily_budget')
    op.drop_column('campaigns', 'state')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'type')
    # ### end Alembic commands ###
